server:
  port: 8082

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    fetch-registry: true
    register-with-eureka: true
