server:
  port: 8086

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?allowPublicKeyRetrieval=true
    username: root # Or a specific user you create
    password: Vishal@123Antiya # Your MySQL root password (or user password)
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
