server:
  port: 8084

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?allowPublicKeyRetrieval=true
    username: root # Or a specific user you create
    password: Vishal@123Antiya #MySQL root password (or user password)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: lLHPdKCN0a4PbN7EQyqWTnJsniYvXsa7TCAQD/wkq+w=
    expiration: 3600000 # Token expiration time (e.g., 1 hour in ms)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
