server:
  port: 8080 # Or any port you prefer for the gateway

spring:
  application:
    name: api-gateway-service #  Service name for registration
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://127.0.0.1:8081 # Route to user-service via Eureka
          predicates:
            - Path=/api/users/**,/api/auth/**
        - id: admin-service-route # Add a new route for admin-service
          uri: http://127.0.0.1:8086 # Route to admin-service
          predicates:
              - Path=/api/admin/**
        - id: product-service-route # Add a new route for admin-service
          uri: http://127.0.0.1:8082 # Route to admin-service
          predicates:
            - Path=/api/products/**
    compatibility-verifier:
        enabled: false # Disable compatibility verifier

#    # Eureka configuration
#    discovery:
#      client:
#        service-url:
#          defaultZone: http://localhost:8761/eureka/ #  Eureka server URL
#        register-with-eureka: true
#        fetch-registry: true
#  security:
#
#
